# Generated by Django 4.1.5 on 2023-01-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=35, verbose_name='商品名稱')),
                ('price', models.IntegerField(default=0, verbose_name='商品價格')),
                ('watched', models.IntegerField(default=0, verbose_name='觀看次數')),
                ('inventory', models.CharField(max_length=20, verbose_name='庫存')),
                ('sold', models.CharField(max_length=20, verbose_name='已賣出')),
                ('discount', models.IntegerField(default=10, verbose_name='折扣(1~9)')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('tag', models.CharField(blank=True, max_length=20, verbose_name='標籤')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品圖片')),
                ('new', models.BooleanField(default=True, verbose_name='新品上市')),
                ('group', models.CharField(choices=[('銀飾類', '銀飾類'), ('生活類', '生活類'), ('其他', '其他')], max_length=10, null=True, verbose_name='分類')),
                ('upload_date', models.DateField(default=django.utils.timezone.now, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='密碼')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='電話')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='電子郵件')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='數量')),
                ('sum', models.IntegerField(default=0, verbose_name='總額')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverwareApp.product', verbose_name='商品ＩＤ')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silverwareApp.myuser', verbose_name='用戶ＩＤ')),
            ],
        ),
    ]
