# Generated by Django 4.1.5 on 2023-01-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silverwareApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sold',
            new_name='is_soldout',
        ),
    ]
